# ~/.bashrc: executed by bash(1) for non-login shells.
[ -z "$PS1" ] && return

PS1="\u@\h:\w# "

if [ $(which micro 2> /dev/null) ]
then
	export EDITOR="micro"
fi
export PAGER="less --mouse --wheel-lines 3"

shopt -s histappend
shopt -s checkwinsize
shopt -s nullglob

HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=500000
PROMPT_COMMAND='history -a'
HISTTIMEFORMAT="%d/%m/%y %T "

if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'

	alias diff='diff --color=auto'
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	. /etc/bash_completion
fi

alias cp='cp -i'
alias mv='mv -i'
alias df='df -h'
alias wget='wget -c'
alias curl='curl --proto-default https'
alias youtube-dl='youtube-dl -f "[height<=720]"'
alias traceroute='traceroute -n'
alias man='man -a'
alias pv='pv -c'
alias less='less --mouse --wheel-lines=3'

alias gitl='git log --pretty --oneline --decorate --graph --all'
alias gitc='git add -A && git commit -am'
alias gits='git status'
alias gitd='git diff'

if [ -f /var/run/reboot-required ]; then echo "REBOOT REQUIRED"; fi
cat /var/log/bash_notify 2> /dev/null
