# ~/.bashrc: executed by bash(1) for non-login shells.
[ -z "$PS1" ] && return

PS1="\u@\h:\w# "

shopt -s histappend
shopt -s checkwinsize

HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=500000
PROMPT_COMMAND='history -a'
HISTTIMEFORMAT="%d/%m/%y %T "

if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

alias ll='ls -l'
alias la='ls -A'
alias lh='ls -lh'
alias l='ls -CF'

alias cp='cp -i'
alias mv='mv -i'
alias du='du -sh'
alias df='df -h'
alias c='clear'
alias mounts='mount | column -t'
alias dd='dd bs=1M status=progress'
alias wget='wget -c'
alias emerge="emerge -a -j$(nproc --all)"
alias youtube-dl='youtube-dl -f mp4'
alias nano='nano -mc'

alias tarballer='cat conf/tarballer | xargs tar -czf config.tgz'

uptime
date
acpi
