ssl_certificate /etc/letsencrypt/live/m0gjr.duckdns.org/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/m0gjr.duckdns.org/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;


ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;

add_header Strict-Transport-Security "max-age=31536000; inlcudeSubDomains" always;
