#!/bin/bash

#func="openssl speed rsa512"
func="sleep 1"

timer(){
	times=$( (time "$@") 2>&1 )

	echo "$times"

	userm=$(echo "$times" | grep user | cut -f2 | cut -d'm' -f1)
	users=$(echo "$times" | grep user | cut -f2 | cut -d'm' -f2 | tr -d '.' | cut -d's' -f1)
	sysm=$(echo "$times" | grep sys | cut -f2 | cut -d'm' -f1)
	syss=$(echo "$times" | grep sys | cut -f2 | cut -d'm' -f2 | tr -d '.' | cut -d's' -f1)

	#echo 60000*$userm+60000*$sysm+$users+$syss
	time=$((60000*$userm+60000*$sysm+$users+$syss))
	echo $time
}

timer "$func"
